export const SELECT_IMAGE_STARTED = "SELECT_IMAGE_STARTED";
export const SELECT_IMAGE_SUCCESS = "SELECT_IMAGE_SUCCESS";
export const SELECT_IMAGE_FAILURE = "SELECT_IMAGE_FAILURE";

export const GENERATE_IMAGE_STARTED = "GENERATE_IMAGE_STARTED";
export const GENERATE_IMAGE_SUCCESS = "GENERATE_IMAGE_SUCCESS";
export const GENERATE_IMAGE_FAILURE = "GENERATE_IMAGE_FAILURE";

export const UPDATE_LOCAL_STATE = "UPDATE_LOCAL_STATE";
